"""Constants for testing modules"""

# * `process_survey`
TEST_CREATE_PARTICIPANT_CODE = "17c9d4zc"
TEST_CREATE_MONTH = 36
TEST_CREATE_VALUES = {
    "Quant Expectation": 10.0,
    "Quant Perception": 3.0,
    "Qual Expectation": 3.0,
    "Qual Perception": 2.0,
}
## Negative qualitative, negative quantitative
TEST_CREATE_CORRECT_NEG_NEG_PARTICIPANT_CODE_EXP = "rvq1b1xn"  # Expectation
TEST_CREATE_CORRECT_NEG_NEG_MONTH_EXP = 48
TEST_CREATE_CORRECT_NEG_NEG_PARTICIPANT_CODE_PERC = "b18fltit"  # Perception
TEST_CREATE_CORRECT_NEG_NEG_MONTH_PERC = 84
## Positive qualitative, negative quantitative
TEST_CREATE_CORRECT_POS_NEG_PARTICIPANT_CODE = "v5ibqv7b"
TEST_CREATE_CORRECT_POS_NEG_MONTH = 12
## Qualitative - no change
TEST_CREATE_CORRECT_ZERO_PARTICIPANT_CODE = "t3lco71m"  # Perception
TEST_CREATE_CORRECT_ZERO_MONTH = 72
## Negative qualitative, positive quantitative
TEST_CREATE_CORRECT_NEG_POS_PARTICIPANT_CODE = "lgvilqkk"  # Expectation
TEST_CREATE_CORRECT_NEG_POS_MONTH = 1


TEST_CREATE_QUANT_EXP_COUNT = 3110.0
TEST_CREATE_QUANT_PERCEP_AVG = 15.3698640

TEST_PIVOT_DF_LEN = 3454
TEST_PIVOT_AVG_QUANT_EXP = 11.8103662
TEST_PIVOT_ERROR_MARGIN = 0.001

TEST_CALCULATE_BIAS_PARTICIPANT_CODE = "01hv4wn4"
TEST_CALCULATE_BIAS_MONTH = 96
TEST_CALCULATE_BIAS_VALUES = {
    "Quant Expectation": 10.0,
    "Quant Perception": 15.0,
    "Actual": 26.85,
    "Upcoming": 55.49,
}
TEST_CALCULATE_BIAS_PERCEPTION = (
    TEST_CALCULATE_BIAS_VALUES["Quant Perception"]
    - TEST_CALCULATE_BIAS_VALUES["Actual"]
)

TEST_CALCULATE_BIAS_EXPECTATION = (
    TEST_CALCULATE_BIAS_VALUES["Quant Expectation"]
    - TEST_CALCULATE_BIAS_VALUES["Upcoming"]
)

TEST_CALCULATE_SENSITIVITY_MONTH = 96
TEST_CALCULATE_SENSITIVITY_PARTICIPANT_CODE = "k78vuxz0"
TEST_CALCULATE_SENSITIVITY_PERCEPTION_VALUE = 0
TEST_CALCULATE_SENSITIVITY_EXPECTATION_VALUE = -0.3626381
TEST_CALCULATE_SENSITIVITY_EXPECTATION_ERROR_MARGIN = 0.0002

TEST_CALCULATE_SENSITIVITY_PARTICIPANT_CODE_NO_NANS = "3lkzrdod"
TEST_CALCULATE_SENSITIVITY_VALUE_NO_NANS = 0
